## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
# you only can run it when you change the runtime to GPU
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### creating tensors with torch.tensor()

https://docs.pytorch.org/docs/stable/torch.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# scalar has no dimension
scalar.ndim

0

X.ndim or X.dim() shows the number of dimensions

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector has magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.dim()

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

Why random tensors? they are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data-> update random numbers -> look at data -> update random numbers`

resource: https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.3708, 0.7026, 0.7134, 0.6667],
        [0.8365, 0.9707, 0.4537, 0.5536],
        [0.5665, 0.9152, 0.6623, 0.6007]])

In [ ]:
random_tensor.dim()

2

In [ ]:
random_tensor2 = torch.rand(1,10,10)
random_tensor2

tensor([[[0.7396, 0.2550, 0.2837, 0.8091, 0.4666, 0.3353, 0.6728, 0.1073,
          0.1135, 0.0305],
         [0.9177, 0.9263, 0.7757, 0.8540, 0.9599, 0.5667, 0.4346, 0.8606,
          0.6616, 0.5508],
         [0.2742, 0.1497, 0.5731, 0.5428, 0.8025, 0.8386, 0.1987, 0.9535,
          0.2960, 0.1555],
         [0.1861, 0.5648, 0.6894, 0.9980, 0.1427, 0.6943, 0.7527, 0.3804,
          0.1258, 0.6826],
         [0.5260, 0.9528, 0.5882, 0.9275, 0.1910, 0.2626, 0.0702, 0.8404,
          0.2161, 0.8665],
         [0.0310, 0.7287, 0.7737, 0.8927, 0.8868, 0.7234, 0.3216, 0.6552,
          0.3791, 0.5884],
         [0.9717, 0.9075, 0.9252, 0.0345, 0.9205, 0.5412, 0.7434, 0.6624,
          0.2738, 0.9692],
         [0.7806, 0.6891, 0.2518, 0.9895, 0.5014, 0.0074, 0.2884, 0.9456,
          0.1659, 0.3166],
         [0.5858, 0.8039, 0.0066, 0.5142, 0.9456, 0.5151, 0.4983, 0.7734,
          0.3540, 0.1544],
         [0.5306, 0.1100, 0.0420, 0.1029, 0.2306, 0.9246, 0.9139, 0.6018,
          0.1347,

In [ ]:
random_tensor2.dim()

3

In [ ]:
random_tensor2.shape

torch.Size([1, 10, 10])

Depending on the context, torch.rand(2, 10, 10):

In image data, it could represent:

2 images, each of size 10×10 → shape (batch=2, height=10, width=10)

In matrix stacks, it could mean:

2 matrices, each 10×10 in size.

In [ ]:
random_tensor3 = torch.rand(2,10,10)
random_tensor3

tensor([[[0.8394, 0.5815, 0.5575, 0.4837, 0.4092, 0.3362, 0.5507, 0.5349,
          0.2606, 0.4811],
         [0.2389, 0.2127, 0.6532, 0.1529, 0.4488, 0.7445, 0.4209, 0.0926,
          0.9926, 0.4928],
         [0.1741, 0.0810, 0.4974, 0.4890, 0.6959, 0.6804, 0.8062, 0.4286,
          0.0673, 0.7391],
         [0.5324, 0.6869, 0.5131, 0.7777, 0.1135, 0.3128, 0.1292, 0.7626,
          0.4909, 0.3421],
         [0.3387, 0.1698, 0.1753, 0.5721, 0.7083, 0.7219, 0.7313, 0.8658,
          0.7200, 0.7616],
         [0.8177, 0.0657, 0.6050, 0.1338, 0.9195, 0.9116, 0.3896, 0.4815,
          0.7961, 0.7267],
         [0.0113, 0.4235, 0.3270, 0.9877, 0.2679, 0.7102, 0.9624, 0.3829,
          0.0466, 0.4182],
         [0.0139, 0.6898, 0.3171, 0.6798, 0.5074, 0.1623, 0.6132, 0.1164,
          0.3551, 0.7055],
         [0.8939, 0.1809, 0.0063, 0.5614, 0.3255, 0.5993, 0.2526, 0.7016,
          0.8896, 0.1144],
         [0.2775, 0.7401, 0.2974, 0.3254, 0.9304, 0.7990, 0.0377, 0.0250,
          0.6762,

In [ ]:
# create a random tensor with similar shape to an image tensor
# torch.rand(size=(224,224,3)) or torch.rand(size=(3,224,224)) if channel comes first
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

torch.rand(size = (3,4)) == torch.rand(3,4)

Zeors and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros* random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size= (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor2.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# use torch.range()
torch.range(0,10)

/tmp/ipython-input-1295656079.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# we also can use arange for deprecated message
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.__version__

'2.8.0+cu126'

In [ ]:
one_to_thousand = torch.arange(start=1,end=1000,step=50)
one_to_thousand

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

in the below code we create ten 0 of shape one to ten. basically we focus on the shape

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device


float 32, or 16 is coming from the precision of computing, basically decides how much details we want in representing of a number

32 requires double memory space compared with 16. it also effect on the speed of the system

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

even when we declare the data type as none, the default data type is float 32

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype= torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what datatype is the tensor (e.g. float32 or 16)
                               device = None, # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with tensor operations

if we change device to "cuda" we need to change cpu to gpu.

requires_grad: PyTorch will calculate the gradiant descent

In [ ]:
# another way of writing float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

sometimes we don't get error for different precision like below scripts

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tenosr = torch.tensor([3,6,9], dtype = torch.long)
int_32_tenosr

tensor([3, 6, 9])

### Getting information from tensors (Tensors attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2915, 0.7340, 0.8945, 0.8094],
        [0.7241, 0.4558, 0.9860, 0.9719],
        [0.7351, 0.4927, 0.0590, 0.0541]])

In [ ]:
some_tensor.size(), some_tensor.shape
# will return the same result

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# find out details about some_tensor
print(some_tensor)
print("data type of tensor: {}".format(some_tensor.dtype))
print("shape of tensor: {}".format(some_tensor.shape))
print("device tensor is on: {}".format(some_tensor.device))

tensor([[0.2915, 0.7340, 0.8945, 0.8094],
        [0.7241, 0.4558, 0.9860, 0.9719],
        [0.7351, 0.4927, 0.0590, 0.0541]])
data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor ([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
# mul is multiplication
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfie:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals: {}".format(tensor * tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor
# this is matrix multiplication too, but it is not common to use

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor [i]* tensor [i]
print(value)

tensor(14)
CPU times: user 1.9 ms, sys: 0 ns, total: 1.9 ms
Wall time: 1.89 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 476 µs, sys: 0 ns, total: 476 µs
Wall time: 375 µs


tensor(14)

the second code for matrix multiplication done by torch.matmul uses a vectorized version of multiplication and that is why it is much faster than the above function

### One of the most common errors in deep learning: shape errors

In [5]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.4751, 0.2279],
        [0.7635, 0.3459]])

In [ ]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[1.8529, 1.9164, 1.9461],
        [1.8330, 2.1815, 2.7303],
        [2.4057, 2.6468, 3.0308]])

what we are doing in tensor multiplication:
resource: https://matrixmultiplication.xyz

In [ ]:
# shapes for matrix multiplication
# torch.matmul == torch.mm
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor's shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print (f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("output: \n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

Finding the min, max, mean, sum, etc (tensor aggregation)

In [6]:
# create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [7]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [8]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [9]:
# find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [11]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

it finds the index of the min/max item

In [12]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
# find the position in tensor that has minimum value with argmin -> returns index position of target tensor where the minimum value occures
x.argmin()

tensor(0)

In [14]:
x[0]

tensor(0)

In [15]:
x.argmax()

tensor(9)

In [16]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by sie (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [17]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

9 = 1 * 9 = 9 * 1= 3 * 3
these are the only valid reshaped tensors

In [18]:
# Add an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [19]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [20]:
x_reshaped = x.reshape(2,9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [21]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [22]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [23]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [24]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [25]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [26]:
x_reshaped = x.reshape(2,2,3)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.],
          [10., 11., 12.]]]),
 torch.Size([2, 2, 3]))

In [27]:
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

#### Changing z changes x (bexause a view of a tensor shares the same memory as the original input)

In [28]:
z[:,0]= 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [29]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [30]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [31]:
x_stacked = torch.stack([x,x,x,x], dim = 2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [32]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.tensor([7, 8, 9])
# Stacking 1D tensors
stacked_tensor_vertically = torch.vstack((a, b, c))
print(stacked_tensor_vertically)
stacked_tensor_horizontally = torch.hstack((a, b, c))
print(stacked_tensor_horizontally)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [33]:
# Stacking 2-D tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
stacked_2d_v = torch.vstack((tensor1, tensor2))
print(f"Stacked 2-D tensors vertically:\n{stacked_2d_v}")
stacked_2d_h = torch.hstack((tensor1, tensor2))
print(f"Stacked 2-D tensors horizontally:\n{stacked_2d_h}")

Stacked 2-D tensors vertically:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Stacked 2-D tensors horizontally:
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [34]:
# torch.squeeze - removes all single dimensions from a target tensor
x_reshaped = x.reshape(1,12)
x_reshaped.shape

torch.Size([1, 12])

In [35]:
x_reshaped.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [36]:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
previous shape: torch.Size([1, 12])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
New shape: torch.Size([12])


In [49]:
# torch.unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [50]:
print(f"previous tensor: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

# remove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
previous shape: torch.Size([12])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
New shape: torch.Size([1, 12])


In [41]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
x.shape

torch.Size([2, 1, 2, 1, 2])

In [43]:
y = torch.squeeze(x)
y.size()
y.shape

torch.Size([2, 2, 2])

In [44]:
y = torch.squeeze(x, 0)
y.size()
y.shape

torch.Size([2, 1, 2, 1, 2])

In [45]:
y = torch.squeeze(x, 1)
y.size()
y.shape

torch.Size([2, 2, 1, 2])

In [46]:
y = torch.squeeze(x, (1, 2, 3))
y.size()
y.shape

torch.Size([2, 2, 2])

In [51]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# with images data we use torch.permute quite often
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") # [color_channels, height, width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [52]:
x_original

tensor([[[0.8449, 0.5474, 0.3790],
         [0.1646, 0.8702, 0.4200],
         [0.9562, 0.3432, 0.2990],
         ...,
         [0.7564, 0.8549, 0.3213],
         [0.0486, 0.5156, 0.2746],
         [0.0534, 0.0793, 0.9326]],

        [[0.1339, 0.0846, 0.4955],
         [0.3097, 0.1646, 0.8155],
         [0.3415, 0.5937, 0.2008],
         ...,
         [0.1791, 0.5213, 0.8090],
         [0.7112, 0.3323, 0.1680],
         [0.0372, 0.6463, 0.3100]],

        [[0.0888, 0.9475, 0.1814],
         [0.0763, 0.0130, 0.9771],
         [0.5762, 0.0070, 0.7638],
         ...,
         [0.3337, 0.3560, 0.2946],
         [0.3502, 0.9836, 0.8188],
         [0.6804, 0.2828, 0.3588]],

        ...,

        [[0.2793, 0.8291, 0.3177],
         [0.6378, 0.9419, 0.6435],
         [0.2021, 0.8694, 0.5958],
         ...,
         [0.2015, 0.6613, 0.9896],
         [0.0226, 0.4491, 0.8943],
         [0.7128, 0.6302, 0.9510]],

        [[0.8207, 0.0735, 0.8803],
         [0.6077, 0.2331, 0.8752],
         [0.

In [53]:
x_original[0,0,0]= 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [56]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [60]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [62]:
x[0][1][1]

tensor(5)

In [63]:
# You can also use ":" to select all of a target dimention
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [65]:
x[:, 1]

tensor([[4, 5, 6]])

How to show the columns?

In [66]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]


tensor([[2, 5, 8]])

In [69]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]
# equals to  x[0][1][1]

tensor([5])

In [71]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [74]:
# Index on x to return 9
x[0][2][2]

tensor(9)

In [75]:
x[0,2,2]

tensor(9)

In [77]:
# Index on x to return 3,6,9
x[:,:, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

The default data type of NumPy is float64 while the default data type of tensor is float32, that causes error, so you need to make them consistent

In [78]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
array.dtype

dtype('float64')

In [80]:
tensor.dtype

torch.float64

In [81]:
torch.arange(1.0,8.0).dtype

torch.float32

If you want to change the data type to float 32:

* array = np.arange(1.0, 8.0)

* tensor = torch.from_numpy(array).type(torch.float32)

In [82]:
# Change the value of the array, what will this do to `tensor`? No

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Tensor to NumPy array
tensor = torch.ones (7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [85]:
# change the tensor, what happens to `numpy_tensor`? it remains unchanged
tensor = tensor +1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random does is "flavour"the randomness.

In [86]:
torch.rand(3,3)

tensor([[0.5875, 0.3012, 0.3595],
        [0.6085, 0.8194, 0.7898],
        [0.6891, 0.5121, 0.3616]])

In [88]:
import torch
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.1927, 0.8682, 0.2102, 0.1216],
        [0.1170, 0.7382, 0.8576, 0.9370],
        [0.6100, 0.4491, 0.7386, 0.3651]])
tensor([[0.8791, 0.5410, 0.9269, 0.5133],
        [0.3994, 0.3474, 0.3385, 0.9175],
        [0.6084, 0.5976, 0.8894, 0.5865]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
# Let's make some random but reproducible tensors
import torch
# set the random seed
RANDOM_SEED = 42

# we should use torch.manual-seed() everytime before creating a new tensor
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs ( and makeing faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.


### 1. Getting a GPU

1. Easiest - use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of a setup and requires the investment of purchasing a GPU, there's lots of options, resource: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: http://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Tue Oct 14 22:29:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   68C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [1]:
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.

E.g. run on GPU if available, else default to CPU
resource: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

### Setup device agnostic code

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
# Count number of devices (GPUs)
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [4]:
# create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3], device = "cpu")
# tensor = torch.tensor([1,2,3]), same result as above script
# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

the result of above cell shows "tensor([1, 2, 3], device='cuda:0')" if we run it on GPU and shows "tensor([1, 2, 3])" if we run it on CPU.

### 4. Moving tensors back to the CPU

In [6]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()
# NumPy doesn't work on GPU

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [7]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [8]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')