# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.6888, 0.4793, 0.9920, 0.9541, 0.7049, 0.9364, 0.1884],
        [0.2088, 0.8349, 0.2256, 0.4837, 0.7609, 0.4492, 0.8300],
        [0.8988, 0.2930, 0.7068, 0.9378, 0.1951, 0.8219, 0.5269],
        [0.0378, 0.7214, 0.7750, 0.7879, 0.0387, 0.1450, 0.4744],
        [0.7179, 0.9539, 0.7528, 0.2974, 0.8482, 0.5860, 0.3552],
        [0.4279, 0.9242, 0.4238, 0.2550, 0.4411, 0.1912, 0.7459],
        [0.9590, 0.1338, 0.0285, 0.7907, 0.8477, 0.2010, 0.8016]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor

Matrix_A = torch.rand(7,7)
Matrix_B = torch.rand(1,7)
Matrix_C= torch.matmul(Matrix_A, Matrix_B.T)

# Perform matrix multiplication
print(Matrix_C)

tensor([[1.5718],
        [1.3006],
        [1.6478],
        [0.9493],
        [1.0679],
        [1.6125],
        [1.3829]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X= torch.rand(7,7)
Y= torch.rand(1,7)
Z= torch.matmul(X,Y.T)

# Matrix multiply tensors
Z, Z.shape

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [3]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
X = torch.rand(2,3).to(device)
Y = torch.rand(2,3).to(device)
X, Y

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [4]:
# Perform matmul on tensor_A and tensor_B
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [6]:
# Find max and min
min_val = Z.min() # or torch.min(Z)
max_val = Z.max() # or torch.max(Z)
print("min value is: {}".format(min_val))
print("max value is: {}".format(max_val))


min value is: 0.3647301495075226
max value is: 0.5617256760597229


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
max_index = torch.argmax(Z)
print("max index value is: {}".format(max_index))

# Find arg min
min_index = torch.argmin(Z)
print("min index value is: {}".format(min_index))

max index value is: 3
min index value is: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [14]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
